# Generated by Django 3.0.5 on 2020-04-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primarytable',
            name='Unique_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
