# Generated by Django 3.0.5 on 2020-04-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_auto_20200424_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='FourthTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_id', models.CharField(default=0, max_length=50)),
                ('meter_total', models.IntegerField(default=0)),
                ('wdr_count_total', models.IntegerField(default=0)),
                ('wdt_count_total', models.IntegerField(default=0)),
                ('cm_count_total', models.IntegerField(default=0)),
                ('cwp_count_total', models.IntegerField(default=0)),
                ('sos_count_total', models.IntegerField(default=0)),
                ('sv_count_total', models.IntegerField(default=0)),
                ('time_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
