# Generated by Django 3.0.5 on 2020-04-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_fourthtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarytable',
            name='Act_EPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Act_PPI',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Act_Width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='DOFE_MTRS',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Descrip',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Doffed_Shift',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Sound_MTRSC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Warp_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Weave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='primarytable',
            name='Weft_Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='primarytable',
            name='Unique_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='primarytable',
            name='loom_no',
            field=models.IntegerField(default=0),
        ),
    ]
