# Generated by Django 3.0.5 on 2020-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20200430_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdtable',
            name='CM_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='CV_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='CW_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='CWp_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='Ctn_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='SY_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='ThTh_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='YSV_count',
            field=models.IntegerField(default=0),
        ),
    ]
