# Generated by Django 3.0.4 on 2020-08-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_auto_20200824_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdtable',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='time_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thirdtable',
            name='time_modified',
            field=models.TimeField(auto_now=True),
        ),
    ]
