# Generated by Django 3.0.5 on 2020-04-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_auto_20200430_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdtable',
            name='cm_count',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='cwp_count',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='sos_count',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='sv_count',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='wdr_count',
        ),
        migrations.RemoveField(
            model_name='thirdtable',
            name='wdt_count',
        ),
    ]
