# Generated by Django 3.0.5 on 2020-05-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_delete_fourthtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdtable',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
